//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChakriDaw.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic
    {
        public int Id { get; set; }
        public System.DateTime PassedYear { get; set; }
        public string InstituteName { get; set; }
        public string Skill { get; set; }
        public int ExamId { get; set; }
        public int BoardId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
