//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChakriDaw.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ApplyStatus { get; set; }
        public int JobPostId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual JobPost JobPost { get; set; }
    }
}
